//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAKKIMDA
    {
        public int ID { get; set; }
        public string BILGILER { get; set; }
        public string EGITIM { get; set; }
        public string ISDENEYIMLERI { get; set; }
    }
}
