//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYETENEKLER
    {
        public byte ID { get; set; }
        public string YETENEK { get; set; }
        public Nullable<byte> DERECE { get; set; }
    }
}
